upstream ml_backend {
    server ml_service_v1:8000 weight=50;
    server ml_service_v2:8000 weight=50;
}

server {
    listen 80;

    location / {
        proxy_pass http://ml_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}